# Site wide configuration

title: robblack007
locale: es_MX
description: El blog de un ingeniero en Mecatrónica.
logo: site-logo.png
search: true
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Makefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Roberto Cadena Vega
  avatar: bio-photo.jpg
  email: robblack00_7@hotmail.com
  disqus-shortname: robblack00_7
  twitter: robblack00_7
  facebook: robblack007
  github: robblack007
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-47826272-1
    verify:    "tY4kjuWTQFnWNtzC4XOPR-d6CWNmFZvSHb1AhEJegxk"
    ad-client:
    ad-slot:
  bing-verify:
